export const BASE_URL = 'http://localhost:8080'

export enum METEO_PARAM_KEYS {
  SOLAR_RADIATION = 'SOLAR_RADIATION',
  PRECIPITATION = 'PRECIPITATION',
  WIND_SPEED = 'WIND_SPEED',
  LEAF_WETNESS = 'LEAF_WETNESS',
  HC_AIR_TEMPERATURE = 'HC_AIR_TEMPERATURE',
  HC_RELATIVE_HUMIDITY = 'HC_RELATIVE_HUMIDITY',
  DEW_POINT = 'DEW_POINT',
  BATTERY = 'BATTERY',
}
